version: "3"

services:
  mysql_app:
      image: node:8
      environment:
        DB_HOST: mysql_db
        DB_USER: app_user
        DB_PASSWORD: app_password
        DB_DRIVER: mysql
      volumes:
        - .:/usr/src/app
      ports:
        - "3000:3000"
      command: "node /usr/src/app/index.js"

  mysql_db:
      image: mysql:5
      environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: app_database
        MYSQL_USER:  app_user
        MYSQL_PASSWORD: app_password
      ports:
        - "3306:3306"
      volumes:
        - ${PWD}/initdb/:/docker-entrypoint-initdb.d