version: "3"

services:
  app:
      build: ${PWD}
      image: example/app
      environment:
        DB_HOST: mysql_db
        DB_USER: app_user
        DB_PASSWORD: app_password
        DB_DRIVER: mysql
      ports:
        - "3000:3000"

  db:
      image: mysql:5
      environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: app_database
        MYSQL_USER:  app_user
        MYSQL_PASSWORD: app_password
      ports:
        - "3306:3306"
      volumes:
        - ${PWD}/initdb/:/docker-entrypoint-initdb.d