version: "3"

services:
  reverse_proxy:
    image: nginx:1
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"

  mysql_app:
      build: ${PWD}
      image: example/app
      environment:
        DB_HOST: mysql_db
        DB_USER: app_user
        DB_PASSWORD: app_password
        DB_DRIVER: mysql

  mysql_db:
      image: mysql:5
      environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: app_database
        MYSQL_USER:  app_user
        MYSQL_PASSWORD: app_password
      ports:
        - "3306:3306"
      volumes:
        - ${PWD}/initdb/mysql/:/docker-entrypoint-initdb.d

  postgres_app:
      build: ${PWD}
      image: example/app
      environment:
        DB_HOST: postgres_db
        DB_USER: app_user
        DB_PASSWORD: app_password
        DB_DRIVER: postgres

  postgres_db:
      image: postgres:9
      environment:
        POSTGRES_DB: app_database
        POSTGRES_USER:  app_user
        POSTGRES_PASSWORD: app_password
      ports:
        - "5432:5432"
      volumes:
        - ${PWD}/initdb/postgres/:/docker-entrypoint-initdb.d